#!/bin/bash
# regenerated by runpod_claim_and_run.py; the record of what ran
env MODEL=allenai/OLMoE-1B-7B-0924 QUANT_TYPE=int8 OFFLOAD_EXPERTS=1 STEPS=100 SEED=1337 DO_GEN=0 EVAL_EVERY=100 E4B_PROFILE_PHASE=train E4B_EXPERT_PROFILE=/workspace/runs/expert_streaming/jobs/profile_olmoe_int8_offload_train_seed1337_steps100/profile.jsonl OUT=/workspace/runs/expert_streaming/jobs/profile_olmoe_int8_offload_train_seed1337_steps100/adapter python -u -m experts4bit_qlora.train
