#!/usr/bin/env python3
# Copyright (c) 2026 Cerin Amroth LLC. MIT.
"""Reduce a K29 receipt directory to RESULTS-k29.md and verdict.json -- from the receipts and nothing else.

    python3 bench/k29/k29_reduce.py <receipt-dir>          # writes <dir>/verdict.json, prints RESULTS-k29.md
    python3 bench/k29/k29_reduce.py --selftest

The rule is grouped-nf4-gemm kernel/PREREG-k29-pinned-charge-cgroup-v2.md's: for every pinned row with N > 0,
r = charged / pow2ceil(N). VOID (not cgroup v2, a failed child, a row not pinned, or the pageable control outside
slope [0.95, 1.10] / R2 >= 0.99) -> CONFIRMED (every r in [0.97, 1.06]) -> PREMIUM (median r > 1.06) -> MIXED.
"""
from __future__ import annotations

import json
import os
import statistics
import sys

R_LO, R_HI = 0.97, 1.06
CONTROL_LO, CONTROL_HI, CONTROL_R2 = 0.95, 1.10, 0.99
MB = 1 << 20


def pow2ceil(n: int) -> int:
    return 1 << (n - 1).bit_length()


def verdict(cgroup: str, data: dict) -> dict:
    rows = data.get("rows", [])
    fits = data.get("fits", {})
    why: list[str] = []
    if cgroup != "v2":
        why.append(f"STOP-1: the box is not cgroup v2 ({cgroup!r})")
    errs = [r for r in rows if "error" in r]
    if errs:
        why.append(f"{len(errs)} child process(es) failed")
    unpinned = [r for r in rows if r.get("mode") == "pinned" and r.get("size_mb") and r.get("is_pinned") is not True]
    if unpinned:
        why.append(f"{len(unpinned)} pinned row(s) not page-locked")
    pg = fits.get("pageable")
    if not pg:
        why.append("no pageable fit")
    elif not (CONTROL_LO <= pg["slope"] <= CONTROL_HI) or pg["r2"] < CONTROL_R2:
        why.append(f"instrument control failed: pageable slope {pg['slope']}, R2 {pg['r2']}")
    rs = [r["delta_mb"] * MB / pow2ceil(r["size_mb"] * MB)
          for r in rows if r.get("mode") == "pinned" and r.get("size_mb") and "delta_mb" in r]
    out = {"r": [round(x, 4) for x in rs], "r_min": round(min(rs), 4) if rs else None,
           "r_max": round(max(rs), 4) if rs else None, "r_median": round(statistics.median(rs), 4) if rs else None,
           "pageable": pg, "pinned_fit": fits.get("pinned"), "cgroup": cgroup}
    if why or not rs:
        return dict(out, verdict="VOID", why=why or ["no pinned rows"])
    if all(R_LO <= x <= R_HI for x in rs):
        return dict(out, verdict="CONFIRMED", why=[f"every pinned r in [{R_LO}, {R_HI}]"])
    if statistics.median(rs) > R_HI:
        return dict(out, verdict="PREMIUM", why=[f"median r {statistics.median(rs):.4f} > {R_HI}"])
    return dict(out, verdict="MIXED", why=[f"r spans {min(rs):.4f}..{max(rs):.4f}"])


def report(d: str) -> str:
    cg = open(os.path.join(d, "cgroup_version.txt")).read().strip() if os.path.exists(os.path.join(d, "cgroup_version.txt")) else "unknown"
    data = json.load(open(os.path.join(d, "k29.json")))
    v = verdict(cg, data)
    json.dump(v, open(os.path.join(d, "verdict.json"), "w"), indent=1)
    env = data.get("env", {})
    lines = ["# Results — K29: what a pinned host byte costs a cgroup v2 container (grouped-nf4-gemm#71)", "",
             "Pre-registration: grouped-nf4-gemm `kernel/PREREG-k29-pinned-charge-cgroup-v2.md`. Generated by "
             "`bench/k29/k29_reduce.py` from the receipt directory and nothing else.", "",
             f"**Verdict: {v['verdict']}** — {'; '.join(v['why'])}", "",
             f"Box: {env.get('gpu')}, driver {env.get('driver')}, torch {env.get('torch')}, cgroup **{cg}** "
             f"(`{env.get('charge_file')}`).", "",
             "| mode | size MB | charged MB | pow2ceil MB | r |", "|---|---|---|---|---|"]
    for r in data.get("rows", []):
        if "delta_mb" not in r:
            lines.append(f"| {r.get('mode')} | {r.get('size_mb')} | error | | |")
            continue
        n = r["size_mb"]
        p2 = pow2ceil(n * MB) // MB if n else 0
        rr = f"{r['delta_mb'] / p2:.4f}" if (r["mode"] == "pinned" and n) else ""
        lines.append(f"| {r['mode']} | {n} | {r['delta_mb']:.1f} | {p2 if r['mode'] == 'pinned' else ''} | {rr} |")
    lines += ["", f"Pinned r: min {v['r_min']}, median {v['r_median']}, max {v['r_max']}. Pageable fit: {v['pageable']}. "
              f"Pinned linear fit (for reference only; the model is the power of two): {v['pinned_fit']}.", ""]
    return "\n".join(lines) + "\n"


def selftest() -> int:
    def rows(r_pinned: float, pageable_slope: float = 1.002, pinned_flag: bool = True):
        out = []
        for n in (340, 700, 2100):
            out.append({"mode": "pinned", "size_mb": n, "delta_mb": pow2ceil(n * MB) / MB * r_pinned, "is_pinned": pinned_flag})
        for n in (0, 340, 700, 2100):
            out.append({"mode": "pageable", "size_mb": n, "delta_mb": n * pageable_slope, "is_pinned": False})
        return out
    def data(rs, slope=1.002, r2=1.0):
        return {"rows": rs, "fits": {"pageable": {"slope": slope, "intercept_mb": 0.0, "r2": r2, "points": 4}}}
    cases = [
        ("v2", data(rows(1.004)), "CONFIRMED"),
        ("v2", data(rows(1.20)), "PREMIUM"),
        ("v1-or-none", data(rows(1.004)), "VOID"),                         # STOP-1
        ("v2", data(rows(1.004, pinned_flag=False)), "VOID"),              # not page-locked
        ("v2", data(rows(1.004), slope=1.3), "VOID"),                      # instrument control
        ("v2", data(rows(1.004), r2=0.9), "VOID"),
        ("v2", data(rows(1.004) + [{"mode": "pinned", "size_mb": 512, "error": "x"}]), "VOID"),
        ("v2", data([{"mode": "pinned", "size_mb": 340, "delta_mb": 512 * 1.004, "is_pinned": True},
                     {"mode": "pinned", "size_mb": 700, "delta_mb": 1024 * 0.90, "is_pinned": True},
                     {"mode": "pinned", "size_mb": 2100, "delta_mb": 4096 * 1.0, "is_pinned": True}]), "MIXED"),
        ("v2", data(rows(0.97)), "CONFIRMED"),                             # the boundary is inside
        ("v2", data(rows(1.061)), "PREMIUM"),
    ]
    bad = 0
    for i, (cg, d, want) in enumerate(cases):
        got = verdict(cg, d)["verdict"]
        ok = got == want
        bad += not ok
        print(f"case {i}: {cg} want {want} got {got} {'ok' if ok else 'FAIL'}")
    print(f"selftest: {len(cases) - bad}/{len(cases)} ok")
    return 1 if bad else 0


if __name__ == "__main__":
    if len(sys.argv) == 2 and sys.argv[1] == "--selftest":
        sys.exit(selftest())
    if len(sys.argv) != 2:
        print(__doc__, file=sys.stderr)
        sys.exit(2)
    sys.stdout.write(report(sys.argv[1]))
