#!/bin/bash
# regenerated by runpod_claim_and_run.py; the record of what ran
python -u scripts/train_mode_adapters.py --model allenai/OLMoE-1B-7B-0924 --train-modes int8 --steps 150 --seed 2027 --adapter-root /workspace/runs/jobs/train_olmoe_int8_resident_seed2027 --out /workspace/runs/jobs/train_olmoe_int8_resident_seed2027/result_rows.jsonl
