"""dequantize_fp8_blocks vs the checkpoint's own convert.py expression.

The reference here is not a reimplementation — it is the literal expression
DeepSeek-V4's ``inference/convert.py`` uses to turn a block-scaled FP8 tensor into
bf16. If the two ever diverge, the dense half of a V4 load is wrong.
"""

import os

import pytest
import torch
import torch.nn.functional as F

from experts4bit_qlora.formats.fp8_blocks import (
    Fp8BlockLinear,
    dequantize_fp8_blocks,
    fp8_block_scale_shape,
)

BLOCK = 128
# Generated by tools/make_v4_fixtures.py from a real checkpoint; skipped when
# absent so CI stays hermetic.
V4_TENSORS = os.environ.get("E4B_V4_TENSORS", "/workspace/v4_expert.safetensors")


def _ref(weight, scale_values):
    """inference/convert.py, verbatim (the `wo_a` dequant branch)."""
    return (
        weight.unflatten(0, (-1, BLOCK)).unflatten(-1, (-1, BLOCK)).float()
        * scale_values[:, None, :, None].float()
    ).flatten(2, 3).flatten(0, 1)


def _fp8(shape, seed):
    g = torch.Generator().manual_seed(seed)
    return (torch.randn(shape, generator=g) / 8).to(torch.float8_e4m3fn)


def _exp_bytes(shape, seed):
    g = torch.Generator().manual_seed(seed)
    return torch.randint(118, 130, shape, generator=g, dtype=torch.uint8)


def test_matches_convert_py_expression():
    w = _fp8((512, 256), 0)
    e = _exp_bytes(fp8_block_scale_shape(w.shape), 1)
    got = dequantize_fp8_blocks(w, e, dtype=torch.float32)
    want = _ref(w, torch.exp2((e.to(torch.int32) - 127).float()))
    assert torch.equal(got, want)


def test_scale_is_a_value_not_an_exponent():
    """The MXFP4 lane wants the raw e8m0 byte; this lane wants 2**(byte-127)."""
    w = torch.full((BLOCK, BLOCK), 1.0).to(torch.float8_e4m3fn)
    e = torch.tensor([[122]], dtype=torch.uint8)  # 2**-5
    got = dequantize_fp8_blocks(w, e, dtype=torch.float32)
    assert torch.equal(got, torch.full((BLOCK, BLOCK), 2.0**-5))


def test_ragged_final_tile():
    """out/in need not be multiples of the block; the last tile is partial."""
    w = _fp8((300, 130), 2)
    assert fp8_block_scale_shape(w.shape) == (3, 2)
    e = _exp_bytes((3, 2), 3)
    got = dequantize_fp8_blocks(w, e, dtype=torch.float32)
    sv = torch.exp2((e.to(torch.int32) - 127).float())
    for i in range(300):
        for j in (0, 129):
            assert got[i, j] == w[i, j].float() * sv[i // BLOCK, j // BLOCK]


def test_int8_and_uint8_storage_agree_with_typed():
    w = _fp8((256, 256), 4)
    e = _exp_bytes((2, 2), 5)
    typed = dequantize_fp8_blocks(w, e, dtype=torch.float32)
    as_u8 = dequantize_fp8_blocks(w.view(torch.uint8), e, dtype=torch.float32)
    as_i8 = dequantize_fp8_blocks(w, e.view(torch.int8), dtype=torch.float32)
    assert torch.equal(typed, as_u8)
    assert torch.equal(typed, as_i8)


def test_mistiled_scale_raises_instead_of_broadcasting():
    w = _fp8((256, 256), 6)
    with pytest.raises(ValueError, match="does not tile"):
        dequantize_fp8_blocks(w, _exp_bytes((2, 1), 7))
    with pytest.raises(ValueError, match="does not tile"):
        dequantize_fp8_blocks(w, _exp_bytes((1, 1), 7))


@pytest.mark.skipif(not os.path.exists(V4_TENSORS), reason="V4 tensor sample not present")
@pytest.mark.parametrize("key", ["layers.18.attn.wq_a", "layers.18.attn.wkv",
                                 "layers.18.attn.wo_b", "layers.18.ffn.shared_experts.w1"])
def test_real_v4_dense_tensors(key):
    w, e = _load_v4(key)
    assert w.dtype == torch.float8_e4m3fn, w.dtype
    assert tuple(e.shape) == fp8_block_scale_shape(w.shape)
    got = dequantize_fp8_blocks(w, e, dtype=torch.float32)
    want = _ref(w, torch.exp2((e.to(torch.int32) - 127).float()))
    assert torch.equal(got, want)
    assert torch.isfinite(got).all()


def _load_v4(key):
    from safetensors import safe_open

    with safe_open(V4_TENSORS, framework="pt", device="cpu") as f:
        return f.get_tensor(key + ".weight"), f.get_tensor(key + ".scale.as_u8")


# --------------------------------------------------------------- Fp8BlockLinear


def _linear(shape=(512, 256), seed=10):
    w = _fp8(shape, seed)
    e = _exp_bytes(fp8_block_scale_shape(shape), seed + 1)
    return Fp8BlockLinear(w, e, compute_dtype=torch.float32), w, e


def test_linear_matches_dense_matmul():
    mod, w, e = _linear()
    x = torch.randn(7, 256)
    want = F.linear(x, dequantize_fp8_blocks(w, e, dtype=torch.float32))
    assert torch.equal(mod(x), want)


def test_linear_keeps_fp8_resident():
    """The whole point: ~1 byte/param resident, not 2."""
    mod, _, _ = _linear((1024, 512))
    assert mod.weight.dtype == torch.float8_e4m3fn
    assert mod.weight.element_size() == 1
    resident = mod.weight.numel() * 1 + mod.scale.numel() * 1
    assert resident < 1024 * 512 * 2, "should be cheaper than a bf16 weight"
    assert mod.dense().dtype == torch.float32


def test_linear_bias_is_applied():
    w = _fp8((256, 128), 20)
    e = _exp_bytes(fp8_block_scale_shape((256, 128)), 21)
    b = torch.randn(256)
    x = torch.randn(3, 128)
    with_bias = Fp8BlockLinear(w, e, b, compute_dtype=torch.float32)(x)
    without = Fp8BlockLinear(w, e, None, compute_dtype=torch.float32)(x)
    assert torch.allclose(with_bias - without, b.expand_as(with_bias), atol=1e-5)


def test_linear_weight_is_frozen():
    mod, _, _ = _linear()
    assert not any(p.requires_grad for p in mod.parameters())
    assert list(mod.parameters()) == [], "storage must be buffers, not trainable params"


def test_linear_rejects_mistiled_scale():
    with pytest.raises(ValueError, match="does not tile"):
        Fp8BlockLinear(_fp8((256, 256), 30), _exp_bytes((1, 2), 31))


@pytest.mark.skipif(not os.path.exists(V4_TENSORS), reason="V4 tensor sample not present")
def test_linear_on_a_real_v4_projection():
    """End-to-end on real bytes: wq_a is [1024, 4096], q_lora_rank x hidden_size."""
    w, e = _load_v4("layers.18.attn.wq_a")
    mod = Fp8BlockLinear(w, e, compute_dtype=torch.float32)
    assert (mod.out_features, mod.in_features) == (1024, 4096)
    x = torch.randn(2, 4096)
    got = mod(x)
    want = F.linear(x, dequantize_fp8_blocks(w, e, dtype=torch.float32))
    assert torch.equal(got, want)
    assert torch.isfinite(got).all()
    # a dead or misread scale would collapse the output scale entirely
    assert got.abs().max() > 1e-3
