#!/bin/bash
# regenerated by runpod_claim_and_run.py; the record of what ran
python -u scripts/eval_adapter_query_modes.py --model allenai/OLMoE-1B-7B-0924 --adapter-root /workspace/runs/jobs/train_olmoe_nf4_resident_seed1337 --query-modes int8 --out /workspace/runs/query_jobs/query_olmoe_train-nf4-resident-seed1337_query-int8-resident/result_rows.jsonl
