#!/bin/bash
# regenerated by runpod_claim_and_run.py; the record of what ran
python -u scripts/train_mode_adapters.py --model allenai/OLMoE-1B-7B-0924 --train-modes nf4-offload --steps 150 --seed 3407 --adapter-root /workspace/runs/jobs/train_olmoe_nf4_offload_seed3407 --out /workspace/runs/jobs/train_olmoe_nf4_offload_seed3407/result_rows.jsonl
