"""Worker-side job claimer/runner for multi-pod validation over a shared RunPod volume.

Topology (docs/RUNPOD_DISTRIBUTED_VALIDATION.md): one controller (owns git, docs, manifests, and
ALL aggregate files) and N workers. A worker's entire write surface is job-local:

    <locks-root>/<job_id>.lock/     claimed atomically (mkdir) — owner identity written inside
    <jobs-root>/<job_id>/           command.sh, run.log, env.json, status.json, result.json,
                                    plus whatever the payload writes (adapter/, sidecars, ...)

Claiming is a single atomic ``os.mkdir`` on the lock dir: it either succeeds (this pod owns the
job, forever — locks are never auto-stolen) or raises (someone else owns it). There is no
check-then-write anywhere. Workers never append to shared JSONL/CSV/Markdown; the controller
aggregates later by reading ``<jobs-root>/*/result.json`` (scripts/summarize_runpod_jobs.py).

The manifest is JSONL, one job per line:

    {"job_id": "...", "job_type": "train|decode|query", "command": ["python", "-u", ...],
     "params": {...}}   # params are echoed into result.json for the summarizer

``{job_dir}`` inside command args is substituted with the job's output directory. The payload
must leave ``result.json`` in the job dir (train/query payloads write result rows the runner
lifts; decode payload writes it directly); if it doesn't, the runner synthesizes a minimal one
from the exit code so failures are never silent.

Usage (one claim loop per GPU, per pod):
    export POD_ID="${POD_ID:-$(hostname)}"
    python scripts/runpod_claim_and_run.py \\
      --manifest runs/job_manifest/olmoe_repeat_jobs.jsonl \\
      --jobs-root runs/jobs --locks-root runs/locks --pod-id "$POD_ID"
"""

import argparse
import json
import os
import subprocess
import sys
from datetime import datetime, timezone

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from mode_matrix_common import read_jsonl  # noqa: E402


def _utc() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _repo_commit():
    # Workers often run from a `git archive` tree (no .git), so git rev-parse yields nothing.
    # The controller pins the shipped SHA in E4B_COMMIT at bootstrap — that is the self-reported
    # commit for this job. Fall back to git only when running inside a real checkout.
    env_commit = os.environ.get("E4B_COMMIT")
    if env_commit:
        return env_commit.strip()
    try:
        r = subprocess.run(
            ["git", "-C", os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "rev-parse", "HEAD"],
            capture_output=True, text=True, timeout=10,
        )
        return r.stdout.strip() or None
    except Exception:
        return None


def _write_json(path, obj):
    with open(path, "w") as f:
        json.dump(obj, f, indent=2, sort_keys=True)
        f.write("\n")


def claim(locks_root, job_id, identity):
    """Atomic claim: mkdir succeeds exactly once. Returns True iff this process owns the job."""
    lock_dir = os.path.join(locks_root, f"{job_id}.lock")
    try:
        os.mkdir(lock_dir)  # THE atomic operation — no check-then-write
    except FileExistsError:
        return False
    _write_json(os.path.join(lock_dir, "owner.json"), identity)
    return True


def run_job(job, jobs_root, identity):
    job_id = job["job_id"]
    job_dir = os.path.join(jobs_root, job_id)
    os.makedirs(job_dir, exist_ok=True)  # ours alone — the lock guarantees it
    command = [str(a).replace("{job_dir}", job_dir) for a in job["command"]]

    with open(os.path.join(job_dir, "command.sh"), "w") as f:
        f.write("#!/bin/bash\n# regenerated by runpod_claim_and_run.py; the record of what ran\n")
        f.write(" ".join(command) + "\n")
    _write_json(os.path.join(job_dir, "env.json"), {
        **identity,
        "torch_env": {k: v for k, v in os.environ.items() if k in
                      ("HF_HOME", "HF_HUB_CACHE", "TRANSFORMERS_CACHE", "PYTORCH_CUDA_ALLOC_CONF", "PYTHONPATH")},
    })
    started = _utc()
    _write_json(os.path.join(job_dir, "status.json"),
                {"status": "running", "started_at": started, **identity})

    with open(os.path.join(job_dir, "run.log"), "w") as lf:
        rc = subprocess.run(command, stdout=lf, stderr=subprocess.STDOUT).returncode
    finished = _utc()

    result_path = os.path.join(job_dir, "result.json")
    result = None
    if os.path.exists(result_path):
        try:
            result = json.load(open(result_path))
        except Exception:
            result = None
    if result is None:
        # Payload wrote rows instead of result.json (train/query payloads), or crashed before
        # writing anything — lift the last row, else synthesize. Failures are never silent.
        rows_path = os.path.join(job_dir, "result_rows.jsonl")
        if os.path.exists(rows_path):
            rows = read_jsonl(rows_path)
            result = rows[-1] if rows else {}
        else:
            result = {}
    result.update(
        job_id=job_id,
        job_type=job.get("job_type"),
        status="pass" if rc == 0 and result.get("status", "pass") == "pass" else "fail",
        exit_code=rc,
        command=" ".join(command),
        started_at=started,
        finished_at=finished,
        **{k: v for k, v in job.get("params", {}).items() if k not in result},
        **identity,
    )
    if result["status"] != "pass" and not result.get("fail_or_skip_reason"):
        result["fail_or_skip_reason"] = f"exit={rc}, see {os.path.join(job_dir, 'run.log')}"
    _write_json(result_path, result)
    _write_json(os.path.join(job_dir, "status.json"),
                {"status": result["status"], "started_at": started, "finished_at": finished, **identity})
    return result["status"]


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--manifest", required=True)
    ap.add_argument("--jobs-root", required=True)
    ap.add_argument("--locks-root", required=True)
    ap.add_argument("--pod-id", default=os.environ.get("POD_ID") or os.uname().nodename)
    ap.add_argument("--only-job-type", default=None, help="claim only jobs of this type")
    ap.add_argument("--max-jobs", type=int, default=0, help="stop after N claimed jobs (0 = drain)")
    ap.add_argument("--dry-run", action="store_true", help="list pending jobs and exit (no claims)")
    args = ap.parse_args()

    jobs = read_jsonl(args.manifest)
    if args.only_job_type:
        jobs = [j for j in jobs if j.get("job_type") == args.only_job_type]
    os.makedirs(args.locks_root, exist_ok=True)
    os.makedirs(args.jobs_root, exist_ok=True)

    pending = [j for j in jobs if not os.path.exists(os.path.join(args.locks_root, f"{j['job_id']}.lock"))]
    print(f"[{args.pod_id}] manifest {args.manifest}: {len(jobs)} jobs, {len(pending)} unclaimed")
    if args.dry_run:
        for j in pending:
            print(f"  pending: {j['job_id']}")
        return 0

    identity = {
        "pod_id": args.pod_id,
        "hostname": os.uname().nodename,
        "pid": os.getpid(),
        "commit": _repo_commit(),
        "claimed_at": _utc(),
    }
    ran = failed = 0
    for job in jobs:  # manifest order; already-locked jobs skip instantly
        if args.max_jobs and ran >= args.max_jobs:
            break
        if not claim(args.locks_root, job["job_id"], {**identity, "command": " ".join(map(str, job["command"]))}):
            continue
        print(f"[{args.pod_id}] claimed {job['job_id']}", flush=True)
        status = run_job(job, args.jobs_root, identity)
        ran += 1
        failed += status != "pass"
        print(f"[{args.pod_id}] {job['job_id']} -> {status}", flush=True)
    print(f"[{args.pod_id}] drained: ran {ran}, failed {failed}")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
