#!/bin/bash
# regenerated by runpod_claim_and_run.py; the record of what ran
env MODEL=allenai/OLMoE-1B-7B-0924 QUANT_TYPE=int8 OFFLOAD_EXPERTS=1 PREFETCH=1 E4B_PROFILE_PHASE=decode E4B_EXPERT_PROFILE=/workspace/runs/expert_streaming/jobs/profile_olmoe_int8_offload_decode_repeat5/profile.jsonl python -u scripts/decode_repeat.py --samples 5 --tokens 128 --job-dir /workspace/runs/expert_streaming/jobs/profile_olmoe_int8_offload_decode_repeat5
