#!/usr/bin/env python3
# Copyright (c) 2026 Cerin Amroth LLC. MIT.
"""Reduce a P55 receipt directory to RESULTS-p55.md — from the receipts and nothing else.

Usage:  python3 bench/p55/p55_reduce.py <receipt-dir> [> RESULTS-p55.md]

The receipt dir is what ``p55_drive.sh`` fetched: ``forensics.txt``, ``class_drawn.txt``,
``result_<arm>.json``, ``logs/<arm>.log``, ``mem_trace.csv``. Every prediction in
``P55-PREREG.md`` is evaluated here against those files, including the ones that refuse —
a reducer that can only confirm is not a reducer ([[feedback_calibrate_detector_against_gold]]).
"""

import csv
import json
import os
import re
import sys

ARMS = ("A_baseline", "B_sync", "C_headroom")
CUDA_INVALID = "invalid argument"
# The kernels whose presence under launch-blocking would REFUTE P3 and reopen #344 as ours.
OURS = re.compile(r"quantize_4bit|dequantize|experts4bit|gemm_int4|gemv_int4|nf4_grouped|gptq", re.I)


def _load(path):
    try:
        with open(path) as fh:
            return json.load(fh)
    except (OSError, ValueError):
        return None


def _text(path):
    try:
        with open(path, errors="replace") as fh:
            return fh.read()
    except OSError:
        return ""


def _host(forensics):
    """Pull the fingerprint fields out of forensics.txt; '?' for anything absent."""
    out = {"gpu": "?", "driver": "?", "cpu": "?", "kernel": "?",
           "mem_total_gib": None, "cgroup": "?"}
    for line in forensics.splitlines():
        if "," in line and "NVIDIA" in line:
            parts = [p.strip() for p in line.split(",")]
            out["gpu"] = parts[0]
            if len(parts) >= 3:
                out["driver"] = parts[-1]
        elif line.startswith("cpu:"):
            out["cpu"] = line.split(":", 1)[1].strip()
        elif line.startswith("kernel:"):
            out["kernel"] = line.split(":", 1)[1].strip()
        elif line.startswith("MemTotal:"):
            out["mem_total_gib"] = int(line.split()[1]) / 1048576
        elif line.startswith("cgroup_limit"):
            out["cgroup"] = line.split(":", 1)[1].strip()
    return out


def _verdict(cond, yes, no, unknown=None):
    if cond is None:
        return f"UNDECIDED — {unknown}"
    return ("HOLDS — " + yes) if cond else ("REFUTED — " + no)


def main(run_dir):
    forensics = _text(os.path.join(run_dir, "forensics.txt"))
    host = _host(forensics)
    class_drawn = _text(os.path.join(run_dir, "class_drawn.txt")).strip() == "1"
    results = {a: _load(os.path.join(run_dir, f"result_{a}.json")) for a in ARMS}
    logs = {a: _text(os.path.join(run_dir, "logs", f"{a}.log")) for a in ARMS}

    print("# Results — P55: does #344's failure reproduce on a low-host-RAM box?\n")
    print("Pre-registration: [`P55-PREREG.md`](P55-PREREG.md). Generated by "
          "`bench/p55/p55_reduce.py` from the receipt directory and nothing else.\n")
    mem = host["mem_total_gib"]
    print("## The host that was drawn\n")
    print(f"| GPU | driver | CPU | kernel | host RAM | cgroup limit | class drawn |")
    print(f"|---|---|---|---|---|---|---|")
    print(f"| {host['gpu']} | {host['driver']} | {host['cpu']} | {host['kernel']} | "
          f"{'?' if mem is None else f'{mem:.0f} GiB'} | {host['cgroup']} | "
          f"{'YES' if class_drawn else '**NO (STOP-1)**'} |\n")
    if not class_drawn:
        print("> **STOP-1 fired.** The drawn box is not of the failing class, so P1 gets no "
              "verdict either way. The arms below are recorded; a pass on this host says "
              "nothing about the class and is not written up as if it did.\n")

    print("## Arms\n")
    print("| arm | status | exception | message |")
    print("|---|---|---|---|")
    for arm in ARMS:
        r = results.get(arm)
        if r is None:
            print(f"| `{arm}` | *no result file* | | |")
            continue
        msg = (r.get("exc_msg") or "").replace("\n", " ")[:110]
        print(f"| `{arm}` | {r.get('status')} | `{r.get('exc_type', '')}` | {msg} |")
    print()

    # ---- P1
    a = results.get("A_baseline")
    if a is None or not class_drawn:
        p1 = None
    else:
        p1 = a.get("status") == "FAILED" and (
            CUDA_INVALID in (a.get("exc_msg") or "")
            or "Cannot allocate memory" in (a.get("exc_msg") or "")
            or "mmap" in (a.get("exc_msg") or ""))
    print("## Predictions\n")
    print("**P1 — reproduction.** " + _verdict(
        p1,
        "the class reproduces #344 unarmed on this host.",
        "this low-RAM host loaded Gemma-4 cleanly (or failed for an unrelated reason). "
        "The memory-headroom reading is refuted and #344 keeps its two dead leads plus this one. "
        "No second box (STOP-3).",
        "no A_baseline result, or STOP-1 withheld the verdict.") + "\n")

    # ---- P2
    b = results.get("B_sync")
    blog = logs.get("B_sync", "")
    armed = "staged synchronisation ON" in blog
    bounded = "[sync]" in blog and "last stage that synchronised clean" in blog
    diagnosed = "MemTotal" in blog and "issues/344" in blog
    if b is None:
        p2 = None
    elif b.get("status") == "OK":
        p2 = None
    else:
        p2 = bool(armed and bounded and diagnosed)
    print("**P2 — the instrumentation names the stage.** " + _verdict(
        p2,
        f"armed={armed}, stage bound printed={bounded}, host+shard diagnosis printed={diagnosed}.",
        f"armed={armed}, stage bound printed={bounded}, diagnosis printed={diagnosed} — "
        "the instrumentation is the defect and is fixed before anything else is read.",
        "B_sync did not fail, so there was nothing for the bound to name.") + "\n")

    # ---- P3
    if b is None or b.get("status") == "OK":
        p3 = None
        p3_why = "B_sync did not fail."
    else:
        tb = b.get("tb") or ""
        ours = OURS.search(tb)
        p3 = not ours
        p3_why = (f"the traceback names `{ours.group(0)}`" if ours
                  else "the failing call is in the shard map or a shard read, not an e4b/gnf4 kernel")
    print("**P3 — the fault is in the mapping, not in an e4b kernel.** " + _verdict(
        p3,
        p3_why + " — #344 is a host-class refusal, not a loader bug.",
        p3_why + " — **#344 reopens as a live loader/kernel bug with a reproduction.** "
        "This is the most valuable outcome available and was registered in advance.",
        p3_why) + "\n")

    # ---- P4
    trace = os.path.join(run_dir, "mem_trace.csv")
    lo = None
    if os.path.exists(trace):
        try:
            with open(trace) as fh:
                vals = [int(r["mem_available_kb"]) for r in csv.DictReader(fh)
                        if r.get("mem_available_kb", "").strip().isdigit()]
            lo = min(vals) / 1048576 if vals else None
        except (OSError, ValueError, KeyError):
            lo = None
    c = results.get("C_headroom")
    if lo is None or c is None or c.get("status") == "OK":
        p4 = None
    else:
        p4 = lo < 49.9          # the largest shard, GiB
    print("**P4 — headroom falls.** " + _verdict(
        p4,
        f"MemAvailable bottomed at {lo:.1f} GiB, below the 49.9 GiB shard.",
        f"MemAvailable never fell below the shard ({lo:.1f} GiB minimum) — the mechanism is "
        "refuted even where the host-class correlation stands.",
        "no usable memory trace, or C_headroom did not fail.") + "\n")

    print("## What this does not say\n")
    print("Nothing about any other checkpoint, nothing about throughput or training, and nothing "
          "about *why* a marginal mapping surfaces as `invalid argument` rather than as ENOMEM. "
          "It cannot exonerate #344's two original machine ids: they are unrentable, and a class "
          "reproduction is not proof that those two boxes failed for the class's reason.\n")
    return 0


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print(__doc__, file=sys.stderr)
        sys.exit(2)
    sys.exit(main(sys.argv[1]))
