#!/bin/bash
# regenerated by runpod_claim_and_run.py; the record of what ran
env QUANT_TYPE=int8 MODEL=allenai/OLMoE-1B-7B-0924 OFFLOAD_EXPERTS=0 python -u scripts/decode_repeat.py --samples 5 --tokens 128 --job-dir /workspace/runs/jobs/decode_olmoe_int8_resident_repeat5
